# Generated by Django 2.2 on 2019-06-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(default='about your country', max_length=555),
        ),
    ]
    
