# Generated by Django 2.2 on 2019-06-22 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_country1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('special', models.CharField(choices=[('bm', 'BATS MAN'), ('bl', 'BOWLER'), ('kr', 'KEEPER'), ('ar', 'ALL ROUNDER')], max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.Country')),
            ],
        ),
    ]
