# Generated by Django 2.1.5 on 2019-06-29 05:06

from django.db import migrations, models
import django.db.models.deletion
import info.models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.Country')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(validators=[info.models.dob_validate]),
        ),
        migrations.AddField(
            model_name='playergroup',
            name='players',
            field=models.ManyToManyField(to='info.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='group1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group1', to='info.PlayerGroup'),
        ),
        migrations.AddField(
            model_name='match',
            name='group2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group2', to='info.PlayerGroup'),
        ),
    ]
