# Generated by Django 2.1.5 on 2019-06-29 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190629_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='info.Country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='stadium',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playergroup',
            name='name',
            field=models.CharField(default='s1', max_length=250),
            preserve_default=False,
        ),
    ]
